version: v1

#
# ISSUE COMMANDS
#
issue:
  labels:
    - prefix: triage
      list: [ "accepted" ]
      multiple: false
      author_association:
        member: true
        owner: true
      needs:
        comment: |
          @$AUTHOR: This issue is currently awaiting triage.

          The triage accepted label can be added by org members by writing `/triage accepted` in a comment.

    - prefix: kind
      list: [ "feature", "docs", "bug-fix", "bug", "governance", "clean-up", "epic" ]
      needs:
        comment: |
          @$AUTHOR: There are no 'kind' label on this issue. Please specify a 'kind' label, thank you!

          * `/kind feature`
          * `/kind docs`
          * `/kind bug`
          * `/kind bug-fix`
          * `/kind governance`
          * `/kind clean-up`
          * `/kind epic`

    - prefix: priority
      multiple: false
      list: [ "critical-urgent", "urgent", "important-soon", "long-term" ]

    - prefix: warning
      list: [ "breaking-change" ]

  chat_ops:
    - cmd: /close
      type: close

    - cmd: /cc
      type: none # does not trigger anything

    - cmd: /assign
      type: assign

    - cmd: /help
      type: label
      label:
        add: help wanted

    - cmd: /duplicate
      type: label
      label:
        add: duplicate

    # REMOVE LABEL COMMANDS
    - cmd: /remove duplicate
      type: label
      label:
        remove: [ 'duplicate' ]

    - cmd: /remove help
      type: label
      label:
        remove: [ 'help wanted' ]

    - cmd: /remove priority
      type: label
      label:
        remove: [ 'priority/critical-urgent', 'priority/urgent', 'priority/important-soon', 'priority/long-term' ]

    - cmd: /remove triage/accepted
      type: label
      label:
        add: needs/triage
        remove: [ 'triage/accepted' ]
      author_association:
        member: true
        owner: true

    - cmd: /remove warning/breaking-change
      type: label
      label:
        remove: [ 'warning/breaking-change' ]

    - cmd: /remove stale
      type: label
      label:
        remove: [ 'stale' ]

    # Remove kind labels
    - cmd: /remove kind/bug
      type: label
      label:
        remove: [ 'kind/bug' ]
    - cmd: /remove kind/bug-fix
      type: label
      label:
        remove: [ 'kind/bug-fix' ]
    - cmd: /remove kind/epic
      type: label
      label:
        remove: [ 'kind/epic' ]
    - cmd: /remove kind/feature
      type: label
      label:
        remove: [ 'kind/feature' ]
    - cmd: /remove kind/clean-up
      type: label
      label:
        remove: [ 'kind/clean-up' ]
    - cmd: /remove kind/docs
      type: label
      label:
        remove: [ 'kind/docs' ]
    - cmd: /remove kind/governance
      type: label
      label:
        remove: [ 'kind/docs' ]

#
# PULL REQUEST COMMANDS
#
pull_request:
  labels:
    - prefix: kind
      list: [ "feature", "docs", "bug-fix", "bug", "governance", "clean-up" ]
      needs:
        comment: |
          @$AUTHOR: There are no 'kind' label on this PR. Please specify a 'kind' label, thank you!

          * `/kind feature`
          * `/kind docs`
          * `/kind bug`
          * `/kind bug-fix`
          * `/kind governance`
          * `/kind clean-up`

    - prefix: priority
      multiple: false
      list: [ "critical-urgent", "urgent", "important-soon", "long-term" ]

    - prefix: merge
      multiple: false
      list: [ "squash", "rebase" ]

    - prefix: warning
      list: [ "breaking-change" ]

  chat_ops:
    - cmd: /close
      type: close

    - cmd: /cc
      type: review

    - cmd: /assign
      type: assign

    - cmd: /lgtm
      type: label
      label:
        add: lgtm
      author_association:
        member: true
        owner: true

    - cmd: /hold
      type: label
      label:
        add: hold/do-not-merge
        remove: [ 'lgtm' ]
      author_association:
        author: true
        collaborator: true
        member: true
        owner: true

    # REMOVE LABEL COMMANDS
    - cmd: /remove lgtm
      type: label
      label:
        remove: [ 'lgtm' ]
      author_association:
        member: true
        owner: true

    - cmd: /remove stale
      type: label
      label:
        remove: [ 'stale' ]

    - cmd: /remove hold
      type: label
      label:
        remove: [ 'hold/do-not-merge' ]
      author_association:
        author: true
        collaborator: true
        member: true
        owner: true

    - cmd: /remove merge
      type: label
      label:
        remove: [ 'merge/rebase', 'merge/squash' ]

    - cmd: /remove priority
      type: label
      label:
        remove: [ 'priority/critical-urgent', 'priority/urgent', 'priority/important-soon', 'priority/long-term' ]

    - cmd: /remove warning/breaking-change
      type: label
      label:
        remove: [ 'warning/breaking-change' ]

    # Remove kind labels
    - cmd: /remove kind/bug
      type: label
      label:
        remove: [ 'kind/bug' ]
    - cmd: /remove kind/bug-fix
      type: label
      label:
        remove: [ 'kind/bug-fix' ]
    - cmd: /remove kind/feature
      type: label
      label:
        remove: [ 'kind/feature' ]
    - cmd: /remove kind/clean-up
      type: label
      label:
        remove: [ 'kind/clean-up' ]
    - cmd: /remove kind/docs
      type: label
      label:
        remove: [ 'kind/docs' ]
    - cmd: /remove kind/governance
      type: label
      label:
        remove: [ 'kind/docs' ]
