architecture:
  description: Core Carbonaut Software Architecture Team
  slack: "#arch"
  members:
  - name: Leonard Pahlke
    github: "leonardpahlke"

data:
  description: Core Carbonaut Data Team
  slack: "#data"
  members:
  - name: Saul O'Driscoll
    github: "liquidsaul"

development:
  description: Core Carbonaut Software Development Team
  slack: "#dev"
  members:
  - name: Leonard Pahlke
    github: "leonardpahlke"

governance:
  description: Core Carbonaut Software Architecture Team
  slack: "#general"
  members:
  - name: Leonard Pahlke
    github: "leonardpahlke"
  - name: Max Körbächer
    github: "mkorbi"
  - name: Sven Pfennig
    github: "0xE282B0"

maintainers:
  description: Core Carbonaut Software Architecture Team
  slack: "#general"
  members:
  - name: Leonard Pahlke
    github: "leonardpahlke"
  - name: Max Körbächer
    github: "mkorbi"
  - name: Sven Pfennig
    github: "0xE282B0"
