on:
  pull_request_target:
    types: [ synchronize, opened, labeled, unlabeled ]
  issues:
    types: [ opened, labeled, unlabeled ]
  issue_comment:
    types: [ created ]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  governance:
    name: Governance
    runs-on: ubuntu-latest
    steps:
      - uses: carbonaut-cloud/carbonaut-governance-bot@v2.0.11
        with:
          github-token: ${{secrets.GOVERNANCE_BOT_TOKEN}}
          config-path: .github/governance.yml